#!/bin/sh

case $1 in
    *.tar)       tar xf $1    ;;
    *.tar.gz)    tar xzf $1   ;;
    *.tar.xz)    tar xf $1    ;;
    *.zip)       unzip $1     ;;
    *.gz)        gunzip $1    ;;
    *.rar)       unrar x $1   ;;
    *)           echo "$1 Can't be Extracted with given tools";;
esac
